--- Makefile
+++ Makefile
@@ -19,6 +19,8 @@ ifeq ($(GCC_VER_49),1)
 EXTRA_CFLAGS += -Wno-date-time	# Fix compile error && warning on gcc 4.9 and later
 endif
 
+EXTRA_CFLAGS += -I$(src)/include
+#else
 EXTRA_CFLAGS += -I$(srctree)/$(src)/include
 
 EXTRA_LDFLAGS += --strip-debug
@@ -226,9 +228,14 @@ _HAL_INTFS_FILES :=	hal/hal_intf.o \
 			hal/led/hal_$(HCI_NAME)_led.o
 
 
+EXTRA_CFLAGS += -I$(src)/platform
+#else
 EXTRA_CFLAGS += -I$(srctree)/$(src)/platform
 _PLATFORM_FILES := platform/platform_ops.o
 
+EXTRA_CFLAGS += -I$(src)/hal/btc
+EXTRA_CFLAGS += -I$(src)/hal/phydm
+#else
 EXTRA_CFLAGS += -I$(srctree)/$(src)/hal/btc
 EXTRA_CFLAGS += -I$(srctree)/$(src)/hal/phydm
 
